name: Publish Packages

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: MineInAbyss/publish-action@v3
        with:
          build-tasks: 'shadowJar publish'
          release-files: 'build/libs/shocky-docs.jar'
          maven-username: ${{ secrets.MAVEN_PUBLISH_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PUBLISH_PASSWORD }}
